- secret:
    name: ptgbot-opendev-quayio
    data:
      quay.io:
        username: opendevorg+ptgbotrobot
        password: !encrypted/pkcs1-oaep
          - wLxGIpS7huEhC7KIT++Zl7i+fNIVhJnm9YRjTabCMhoPRzKnnpiLETdiAb+63n7xXaqoA
            YRUt1zsVS3EHIEAK6chmH2hSq9sHxweCIAgq6H1gVwN+DOYYyv2BfHzUIQcFs3zpsdNLe
            vXC4q6GcIwAwe9qSOJ875CDsChvlbyhpwEi5C+o+w6XOO/uZMNRCL4B+vssM6IXL+inmb
            k4n1okvLvLqniQFrWvB1c1AGMJ/9lOKLdHfducd1FqKEist1K6QaA1TR1y19P9fubN78W
            9D707NhvcicrCZjwrx1r0Gidi40E9cyNHot3yCeWCQeJ5+6Qku3AXsxTascyaF76LVQMy
            FKkHv2pL2PabtQzdj96doaGJ8upwORYGLsEILMXCjRoH9HgRx3NNIfZEvQFcvDFz92gnm
            66BCiE1EWfz2Q9nYcfKruGoSKTgLcHL3beoGsSeGJtImMDC3IR+uDjom8fekm8XBu4Pr6
            bQ8VtV30IkSwJXFc7Rtz/3f6qaj0e9wgfkdZbulxhFxBJHoeoYaJHxZGRKiELpTNnqM3Y
            1Pkn18xNmfrZjGxR+88WI5XO+E+RJpn76cVitRFA6XIq6tjWSxWtMdUFtptN69HcR7rQ0
            gkYNk7+UIP78gWzbK0/uv2rXwnGw35yVotBZdpyMaiUv5eq+3iwKCW1+oDGjbw=
        # No api token as we won't need to create new repos for ptgbot

- job:
    name: ptgbot-build-opendev-image
    parent: opendev-build-container-image
    description: Build OpenDev Docker images for statusbot
    requires:
      - python-builder-3.9-bullseye-container-image
      - python-base-3.9-bullseye-container-image
    provides: ptgbot-container-image
    vars: &ptgbot_opendev_image_vars
      zuul_work_dir: src/opendev.org/openstack/ptgbot
      promote_container_image_method: intermediate-registry
      promote_container_image_job: ptgbot-upload-opendev-image
      container_command: docker
      container_images:
        - context: .
          registry: quay.io
          repository: quay.io/opendevorg/ptgbot
          namespace: opendevorg
          repo_shortname: ptgbot
          repo_description: An IRC bot for managing team gatherings
          target: ptgbot

- job:
    name: ptgbot-upload-opendev-image
    parent: opendev-upload-container-image
    description: Build OpenDev statusbot Docker images and upload to Docker Hub.
    requires:
      - python-builder-3.9-bullseye-container-image
      - python-base-3.9-bullseye-container-image
    provides: ptgbot-container-image
    vars: *ptgbot_opendev_image_vars
    secrets:
      - name: container_registry_credentials
        secret: ptgbot-opendev-quayio
        pass-to-parent: true

- job:
    name: ptgbot-promote-opendev-image
    parent: opendev-promote-container-image
    description: Promote previously uploaded ptgbot Docker images.
    vars: *ptgbot_opendev_image_vars
    secrets:
      - name: container_registry_credentials
        secret: ptgbot-opendev-quayio
        pass-to-parent: true
- project:
    check:
      jobs:
        - tox-pep8
        - tox-py38:
            nodeset: ubuntu-focal
        - ptgbot-build-opendev-image
    gate:
      jobs:
        - tox-pep8
        - tox-py38:
            nodeset: ubuntu-focal
        - ptgbot-upload-opendev-image
    promote:
      jobs:
        - ptgbot-promote-opendev-image
