- secret:
    name: ptgbot-opendev-quayio
    data:
      quay.io:
        username: opendevorg+ptgbotrobot
        password: !encrypted/pkcs1-oaep
          - tbHiQcOiIzZhSNAPhWQ/SKWMbwPyj+MRa0fNV3XKtRcIyVKsRDnnkdpw1VDZ1JHivZa96
            vWUKfhxejPGdkiaWkOn2wOALTdtBEl7hgFl2tC5rOmvRxOnACX+PvXkqiORyqzdI4sgDB
            equs+eXSIv15MNf4ylRhdxTZKt7BrKLtPVpNblgX+fijktVSz14XY9064mO8O2v5Uz1S2
            4IrVsQ/ft2pPNlkI+H0zSpRxkXE1OOjggwYIivDoSWgxWG4Ix8scsnyWZDsG18hyishHU
            oC+Com6/lgu1ad6TA9p92ayYDjBrgZcBXBEE3d/+IEhYeTNHTCyQ4+svF90T/BjkFJ/mZ
            jwCD27yrFRNbUB5MkgOPfbhhJMb+dBoOr2YoUvFRCXT5XN74dL/9K6YeP3CmwNJL8yj/G
            hCLcdPAPYR31to30BdxJSCKUh4yivJW7XMzhgpI1+q0NNvSkBiY1kfZDyAxM7xXR6WlqI
            ugAMUcDGgHVFMYGJC4C2JvU9OmrFvj+Svzkv8O1je85KebovUC+fF4M0p9aEyQJKoaSWV
            6OfnehTpVEf0ftCT9JgKzdCVuWa8DueMgJG2ztVuiKsChFnkZzDMoTqM/eiz2AOnP43+f
            jmbzds7hyxJzF/5ryawz12pEBaqUt16WgpC6aexkCiInNQ1K60OYnd85Vo2LgE=
        # No api token as we won't need to create new repos for ptgbot

- job:
    name: ptgbot-build-opendev-image
    parent: opendev-build-container-image
    description: Build OpenDev Docker images for statusbot
    requires:
      - python-builder-3.11-bookworm-container-image
      - python-base-3.11-bookworm-container-image
    provides: ptgbot-container-image
    vars: &ptgbot_opendev_image_vars
      zuul_work_dir: src/opendev.org/openstack/ptgbot
      promote_container_image_method: intermediate-registry
      promote_container_image_job: ptgbot-upload-opendev-image
      container_command: docker
      container_images:
        - context: .
          registry: quay.io
          repository: quay.io/opendevorg/ptgbot
          namespace: opendevorg
          repo_shortname: ptgbot
          repo_description: An IRC bot for managing team gatherings
          target: ptgbot

- job:
    name: ptgbot-upload-opendev-image
    parent: opendev-upload-container-image
    description: Build OpenDev statusbot Docker images and upload to Docker Hub.
    requires:
      - python-builder-3.11-bookworm-container-image
      - python-base-3.11-bookworm-container-image
    provides: ptgbot-container-image
    vars: *ptgbot_opendev_image_vars
    secrets:
      - name: container_registry_credentials
        secret: ptgbot-opendev-quayio
        pass-to-parent: true

- job:
    name: ptgbot-promote-opendev-image
    parent: opendev-promote-container-image
    description: Promote previously uploaded ptgbot Docker images.
    vars: *ptgbot_opendev_image_vars
    secrets:
      - name: container_registry_credentials
        secret: ptgbot-opendev-quayio
        pass-to-parent: true
- project:
    check:
      jobs:
        - tox-pep8
        - tox-py311:
            nodeset: ubuntu-jammy
        - ptgbot-build-opendev-image
    gate:
      jobs:
        - tox-pep8
        - tox-py311:
            nodeset: ubuntu-jammy
        - ptgbot-upload-opendev-image
    promote:
      jobs:
        - ptgbot-promote-opendev-image
